// <auto-generated />
namespace AutoMoto.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeincar2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeincar2));
        
        string IMigrationMetadata.Id
        {
            get { return "201611201105360_changeincar2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
